server:
  port: 8086
spring:
  flyway:
    locations = classpath:db.migration
  application:
    name: marketplace

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: trcvbr18

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true