server:
  port: 8086
spring:
  application:
    name: marketplace

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: developertest
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect